### ISSUE TITLE
Error in running set_frequency_example

### ISSUE THREAD

**Issue by jcmanalo33** [Schlabonski/evalcontrol#8]
Hi, can you help me with the errors below please? Thanks

File "C:\evalcontrol\venv\lib\site-packages\usb\backend\libusb1.py", line 600, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform
Exception ignored in: <function AD9959.__del__ at 0x000001EE71A63E58>
Traceback (most recent call last):
  File "C:\evalcontrol\evalcontrol\ad9959.py", line 86, in __del__
    usb.util.dispose_resources(self.dev)
AttributeError: 'AD9959' object has no attribute 'dev'

**Comment by DuncanB6** [comment]
Hi @jcmanalo33,

Although I'm not the owner of this library, I ran into the same issue. I found this was caused by having the incorrect USB backend installed. Make sure you have the libusb file in your System32 folder, and that the path to that folder is added to your Windows PATH variable (assuming you're on windows). Although I'm sure there's a better way to do this, you can get the libusb DLL if you install libusb using pip or equivalent, then just find it in the package install directory. 

Schlabonski has some of this info in the README, although some links are a bit outdated.

**Comment by jcmanalo33** [comment]
Thanks @DuncanB6. I'm using windows. Tried to install the driver using Zadig - WinUSB (v6.1.7600.16385). Error is gone but nothing happens - multiplier or frequency not set. Are you using different driver like libusb-win32 (v1.2.7.3), libusbK (v3.1.0.0), or other?  Thanks

**Comment by DuncanB6** [comment]
Hi @jcmanalo33, I used the WinUSB driver so it should be OK. A few people (including myself) seem to have had issues with the board not initializing properly when using this API. To test if this is your case, you could set your frequency and multiplier with the Analog Devices Eval Software, then switch to the API and see if you can change these settings. If it's not that, I'm afraid I don't know.
